name: grinder_coveralls
version: 0.1.0

author: CÃ©dric Belin <cedric@belin.io>
description: Coveralls plug-in for the Grinder build system.
documentation: https://cedx.github.io/grinder-coveralls
homepage: https://github.com/cedx/grinder-coveralls

environment:
  sdk: '>=2.0.0-dev.69 <3.0.0'

dependencies:
  coverage: ^0.12.2
  coveralls: ^3.1.0
  grinder: ^0.8.3

dev_dependencies:
  analyzer: ^0.32.4
  test: ^1.3.0
